services:
  zenn:
    image: node:24.0.2-slim
    volumes:
      - .:/usr/src/app
      - node_modules_volume:/usr/src/app/node_modules

    working_dir: /usr/src/app

    command: >
      /bin/sh -c
      "npm install && npx zenn preview"

    ports:
      - "8000:8000"

volumes:
  node_modules_volume: